# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'XCGLogger', '~> 6.0.2'

target 'ObjcExceptionBridging (iOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcExceptionBridging (iOS)

end

target 'ObjcExceptionBridging (macOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcExceptionBridging (macOS)

end

target 'ObjcExceptionBridging (tvOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcExceptionBridging (tvOS)

end

target 'ObjcExceptionBridging (watchOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcExceptionBridging (watchOS)

end

target 'XCGLogger (iOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCGLogger (iOS)

end

target 'XCGLogger (macOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCGLogger (macOS)

end

target 'XCGLogger (tvOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCGLogger (tvOS)

end

target 'XCGLogger (watchOS)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCGLogger (watchOS)

end
